# Introduction of Numpy

## What is Numpy ?
* Numpy stand for Numercial Python. It is used for working with numbers, mathmatical operations, and large datasets.


## Why do we use Numpy ?
* Faster than normal Python lists.
* Used for arrays(1D,2D,3D _ _ _).
* Easy mathmatical operations (Addition, Subtraction, Multiplication, Division, Square  root, mean, median, Dot Product, Matrix Multiplications)
* Used in Data Analytics & Machine Learning
  

## How to install Numpy
* In Windows/Mac/Linux
   * Open terminal or command prompt:
     * pip install numpy
* In Jupyter notebook
   * Just run
     * !Pip install numpy

## How to import Numpy

In [1]:
import numpy as np

* **import**:- means to bring a library into your Python program
* **numpy**:- NumPy is a Python library
* **as**:- as means give a short name (alias)
* **np**:- np is the short name for NumPy

print(dir(np))

*print(dir(np)) shows all the functions and attributes available in the NumPy library.*

## Numpy function
* **Array Creation Functions:-** (array,zeros,ones,eye,full)
* **Mathematical Functions:-** (sum,mean,max,min,sqrt)
* **Shape & Dimension Functions:-** (ndim,shape,size)
* **Random Functions:-** (random.rand,random.randint,random.randn)
* **Sequence Functions:-** (arange,linspace)
* **Matrix Functions:-** (dot,transpose)


### Array Creation Functions :-

**Array:-** *An array is a data structure that stores multiple values of the same data type in a single variable.*

In [28]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

**Zeros:-** *np.Zeros() is a function that creates an array filled with 0 values.*

In [7]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**Ones:-** *np.Ones() is a function that created an array filled with values 1.*

In [8]:
a=np.ones((2,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**eye:-** *The Eye() function in NumPy is used to create an identity matrix, where the diagonal elements are 1 and all other elements are 0.*

In [10]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Full:-** *The full() function is used to create an array filled with a specified value.*

In [12]:
arr=np.full((3,3),7)
arr

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

### Mathematical Functions :-

**sum:-** *sum() is a function used to add all the elements of an array.*

In [14]:
arr = np.array([10, 20, 30, 40])
print(arr.sum())

100


**mean:-** *mean() is used to calculate the average of element.*

In [16]:
arr = np.array([1, 2, 3, 4])
print(arr.mean())

2.5


**max:-** *max() is a function used to find the largest value in an array.*

In [17]:
arr = np.array([10, 25, 7, 40, 18])
print(arr.max())

40


**min:-** *min() is a function used to find the smallest value in an array.*

In [19]:
arr = np.array([10, 25, 7, 40, 18])
print(arr.min())

7


**sqrt:-** *sqrt() is a function used to find the square root of each element in an array.*

In [27]:
arr = np.array([4,9,16,25])
print(np.sqrt(arr))

[2. 3. 4. 5.]


### Shape & Dimension Functions :-

**ndim:-** *ndim is used to find the number of dimensions of an array.*

In [30]:
arr = np.array([10, 20, 30,40])
print(arr.ndim)

1


**shape:-** *shape is used to find the number of rows and columns (dimensions) of an array.*

In [33]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


**size:-** *size is used to find the total number of elements in an array.*

In [35]:
arr = np.array([10, 20, 30, 40,50,60])
print(arr.size)

6


### Random Functions :-

**random.rand:-** *random.rand() is used to create an array of random numbers between 0 and 1.*

In [37]:
arr = np.random.rand(3,3)
print(arr)

[[0.17725402 0.88490479 0.21622332]
 [0.93222046 0.86218035 0.58038008]
 [0.84701837 0.07289515 0.31042641]]


**random.randint:-** *It is random whole number between a start and end value.*

In [39]:
arr=np.random.randint(0,20,(3,3))
print(arr)

[[11  6  1]
 [ 6 19  1]
 [ 1 13  2]]


**random.randn:-** *random.randn() give random number that can negative, Zero, positive.*

In [41]:
arr=np.random.randn(2,3)
print(arr)

[[ 2.36957659  0.53746684 -0.81049271]
 [-0.7532348  -0.36770838  0.2417695 ]]


### Sequence Functions :-

**arange:-** *arange() is used to create a sequence of numbers within a specified range.*

In [43]:
arr=np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


**Linspace:-** *linspace() is used to create a sequence of evenly spaced numbers between a start and an end value.*

In [45]:
arr=np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


### Matrix Functions :-

**Dot:-** *dot() is used to perform matrix multiplication between two arrays.*

In [48]:
a = np.array([1, 2, 3,4,5])
b = np.array([6,7,8,9,10])
result = np.dot(a, b)
print(result)


130


**Transpose:-** *transpose() is used to swap rows and columns of an array.*

In [50]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


### Other Functions :-

**argmax:-** *argmax() is used to find the index of the maximum value in an array.*

In [53]:
arr = np.array([1,2,3,4,5])
print(np.argmax(arr))

4


**agrmin:-** *argmin() is used to find the index of the minimum value in an array.*

In [61]:
arr = np.array([10, 45, 23, 5, 34])
print(np.argmin(arr))

3


**std:-** *std() is used to calculate the standard deviation of elements in an array, which shows how much the values deviate from the mean.*

In [62]:
arr = np.array([10, 20, 30, 40, 50])
print(np.std(arr))

14.142135623730951


**flatten:-** *flatten() is used to convert a multi-dimensional array into a one-dimensional (1D) array.*

In [64]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr.flatten())

[1 2 3 4 5 6]


**ravel:-** *ravel() is used to convert any array into a 1D(faltend) array.*

In [65]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr.ravel())

[1 2 3 4 5 6]


**reshape:-** *reshape() is used to change the shape of an array without changing its data.*

In [67]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


**diag:-** *diag() is used to extract the diagonal elements of a matrix or create a diagonal matrix from a 1D array.*

In [68]:
arr = np.array([1, 2, 3, 4])
print(np.diag(arr))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


### Arithmetic Operations

In [3]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
print(a + b)

print(a - b)

print(a * b)

print(a / b)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


### Sort Array

In [4]:
arr = np.array([40, 10, 30, 20])
print(np.sort(arr))

[10 20 30 40]


## Difference Between NumPy Array and Python List

| Basis | NumPy Array | Python List |
|------|-------------|-------------|
| Data Type | Same type of elements | Different types of elements |
| Speed | Faster | Slower |
| Memory | Uses less memory | Uses more memory |
| Mathematical Operations | Directly supported | Need loops |
| Performance | Best for large data | Better for small data |
| Dimension | Supports multi-dimensional | Mostly one-dimensional |
| Library | NumPy library | Python built-in |


In [6]:
list1 = [1, 2, 3, 4]
array1 = np.array([1,2,3,4])
print("List Addition: ",list1 + list1)
print("Numpy array Addition : ", array1 +array1)

List Addition:  [1, 2, 3, 4, 1, 2, 3, 4]
Numpy array Addition :  [2 4 6 8]


## Try these  question

* Using NumPy, create a 3×3 random matrix.    **hint(random.rand())**

*  Create a 4×5 matrix of zeros using NumPy.   **hint(zeros())**

* Create a 4×5 matrix of ones using NumPy.      **hint(ones())**

* Print the shape and size of both matrices.    **hint(shape(),size())**

* Create a 3x3 identity matrix.      **hint(eye())**

* create a 2x4 matrix filled with value 9.    **hint(full())**

